server:
  port: 10001

spring:
  application:
    name: JTYJY-API-GATEWAY
  profiles:
    active: @env@
  datasource:
    url: jdbc:mysql://192.168.2.31:3306/jtyjy_gateway?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: mysql
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 192.168.5.106:31559
        group: local
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.cloud.gateway.filter.LoadBalancerClientFilter: TRACE