server:
  port: 11001

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: JTYJY-API-GATEWAY
  profiles:
    active: @env@
  datasource:
    url: jdbc:mysql://192.168.2.31:3306/jtyjy_gateway?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: mysql
    password: 123456
  redis:
    #数据库索引
    database: 0
    host: 192.168.5.106
    port: 30538
    #连接超时时间
    timeout: 5000
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 192.168.5.106:31559
        group: @env@
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.cloud.gateway.filter: TRACE